use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :zam, ZamWeb.Endpoint,
  http: [port: 8080, compress: true],
  url: [host: "fantasticsearchwebsitename.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:zam, :vsn)

# Do not print debug messages in production
config :logger, level: :info



# ## Using releases (Elixir v1.9+)
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start each relevant endpoint:
#
config :zam, ZamWeb.Endpoint, server: true

import_config "prod.secret.exs"
